# Generated by Django 5.0.4 on 2026-09-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_geofence_caregiver_and_exit_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DOSE_REMINDER', 'Dose Reminder'), ('MISSED_DOSE_ALERT', 'Missed Dose Alert'), ('CAREGIVER_ALERT', 'Caregiver Alert'), ('REFILL_ALERT', 'Refill Alert'), ('PRESCRIPTION_EXPIRY', 'Prescription Expiry'), ('SUBSCRIPTION_EXPIRY', 'Subscription Expiry'), ('ANOMALY_ALERT', 'Anomaly Alert'), ('CAREGIVER_INVITE', 'Caregiver Invite'), ('SYSTEM', 'System Notification'), ('WELCOME', 'Welcome'), ('ACCOUNT_SECURITY', 'Account Security'), ('GEOFENCE_EXIT', 'Geofence Exit Alert'), ('HIGH_RISK_ALERT', 'High Risk Alert'), ('DOCTOR_ALERT', 'Doctor Review Alert'), ('AI_INSIGHT', 'AI Insight'), ('AI_ADHERENCE_NUDGE', 'AI Adherence Nudge'), ('AI_ADHERENCE_REMINDER', 'AI Adherence Reminder')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('DOSE_REMINDER', 'Dose Reminder'), ('MISSED_DOSE_ALERT', 'Missed Dose Alert'), ('CAREGIVER_ALERT', 'Caregiver Alert'), ('REFILL_ALERT', 'Refill Alert'), ('PRESCRIPTION_EXPIRY', 'Prescription Expiry'), ('SUBSCRIPTION_EXPIRY', 'Subscription Expiry'), ('ANOMALY_ALERT', 'Anomaly Alert'), ('CAREGIVER_INVITE', 'Caregiver Invite'), ('SYSTEM', 'System Notification'), ('WELCOME', 'Welcome'), ('ACCOUNT_SECURITY', 'Account Security'), ('GEOFENCE_EXIT', 'Geofence Exit Alert'), ('HIGH_RISK_ALERT', 'High Risk Alert'), ('DOCTOR_ALERT', 'Doctor Review Alert'), ('AI_INSIGHT', 'AI Insight'), ('AI_ADHERENCE_NUDGE', 'AI Adherence Nudge'), ('AI_ADHERENCE_REMINDER', 'AI Adherence Reminder')], max_length=40, unique=True),
        ),
    ]
