# Generated by Django 5.0.4 on 2026-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('PUSH', 'Push Notification (FCM/APNs)'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('TELEGRAM', 'Telegram'), ('VOICE', 'Voice Call'), ('IN_APP', 'In-App')], default='IN_APP', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('PUSH', 'Push Notification (FCM/APNs)'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('TELEGRAM', 'Telegram'), ('VOICE', 'Voice Call'), ('IN_APP', 'In-App')], max_length=20),
        ),
    ]
