# Generated by Django 5.0.4 on 2026-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_physicalcompartment_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='schedule_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='tare_weight_grams',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='device',
            name='total_weight_grams',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dosesession',
            name='device_session_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dosesession',
            name='slot_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('SYNC_SCHEDULE', 'Sync Schedule'), ('PREPARE_COMPARTMENT', 'Prepare Compartment'), ('FORCE_OPEN_LID', 'Force Open Lid'), ('CANCEL_DISPENSE', 'Cancel Dispense'), ('START_FILL_MODE', 'Start Fill Mode'), ('NEXT_COMPARTMENT', 'Next Compartment (Fill)'), ('END_FILL_MODE', 'End Fill Mode'), ('RESET_FLAGS', 'Reset Daily Dispense Flags'), ('LOCK_DEVICE', 'Lock Device'), ('UPDATE_DISPLAY', 'Update Display'), ('FIRMWARE_UPDATE', 'Firmware Update'), ('SYNC_TIME', 'Sync Time'), ('GATE_LOCK', 'Lock Gate'), ('GATE_UNLOCK', 'Unlock Gate'), ('OPEN_GATE', 'Open Gate'), ('READ_FILL_WEIGHT', 'Read Fill Weight'), ('TRIGGER_DOSE', 'Trigger Dose Now'), ('READ_WEIGHT', 'Read Weight'), ('SYNC_CONFIG', 'Sync Config Bundle')], max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='event_type',
            field=models.CharField(choices=[('DEVICE_BOOT', 'Device Boot'), ('HEARTBEAT', 'Heartbeat'), ('COMPARTMENT_ROTATED', 'Compartment Rotated'), ('HAND_DETECTED', 'Hand Detected'), ('LID_OPENED', 'Lid Opened'), ('LID_CLOSED', 'Lid Closed'), ('DOSE_STARTED', 'Dose Started (RTC triggered)'), ('WEIGHT_READING', 'Weight Reading'), ('DOSE_TAKEN', 'Dose Taken'), ('DOSE_TIMEOUT', 'Dose Timeout (Missed)'), ('DOSE_SKIPPED', 'Dose Skipped'), ('DOSE_DUPLICATE_BLOCKED', 'Duplicate Dose Blocked'), ('COMMAND_ACKNOWLEDGED', 'Command Acknowledged'), ('FILL_STARTED', 'Fill Mode Started'), ('FILL_CONFIRMED', 'Fill Confirmed by User'), ('FILL_COMPLETED', 'Fill Mode Completed'), ('DOSE_MISSED', 'Dose Missed'), ('COMPARTMENT_OPEN', 'Compartment Opened'), ('LOW_BATTERY', 'Low Battery'), ('TAMPER', 'Tamper Detected'), ('DEVICE_ON', 'Device Powered On'), ('DEVICE_OFF', 'Device Powered Off')], max_length=40),
        ),
    ]
