# Generated by Django 5.0.4 on 2026-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0002_geofence_caregiver_and_exit_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofencezone',
            name='points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='shape_type',
            field=models.CharField(choices=[('CIRCLE', 'Circle'), ('POLYGON', 'Custom Shape')], default='CIRCLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='geofencezone',
            name='radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
