# Generated by Django 5.0.4 on 2026-09-15 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('chat_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('AWAITING_CONTACT', 'Awaiting Phone Share'), ('AWAITING_OTP', 'Awaiting OTP'), ('AWAITING_DOSE_RESPONSE', 'Awaiting Dose Response')], default='IDLE', max_length=30)),
                ('state_data', models.JSONField(default=dict)),
                ('last_activity_at', models.DateTimeField()),
                ('onboarding_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_sessions',
            },
        ),
        migrations.CreateModel(
            name='TelegramInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('message_body', models.TextField()),
                ('intent', models.CharField(blank=True, choices=[('DOSE_YES', 'Dose Taken'), ('DOSE_NO', 'Dose Not Taken'), ('DOSE_SKIP', 'Dose Skipped'), ('HELP', 'Help'), ('STATUS', 'Status Request'), ('UNKNOWN', 'Unknown')], max_length=15, null=True)),
                ('telegram_update_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='telegram_bot.telegramsession')),
            ],
            options={
                'db_table': 'telegram_interaction_logs',
            },
        ),
        migrations.AddConstraint(
            model_name='telegraminteractionlog',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_update_id__isnull', False)), fields=('telegram_update_id',), name='uq_tg_update_id'),
        ),
    ]
