# Generated by Django 5.0.4 on 2026-09-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsession',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='telegramsession',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='telegramsession',
            name='language',
            field=models.CharField(choices=[('hi', 'Hindi'), ('en', 'English')], default='hi', max_length=5),
        ),
        migrations.AlterField(
            model_name='telegraminteractionlog',
            name='intent',
            field=models.CharField(blank=True, choices=[('DOSE_YES', 'Dose Taken'), ('DOSE_NO', 'Dose Not Taken'), ('DOSE_SKIP', 'Dose Skipped'), ('HELP', 'Help'), ('STATUS', 'Status Request'), ('REPORT', 'Adherence Report'), ('MENU', 'Main Menu'), ('UNKNOWN', 'Unknown')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='telegramsession',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('AWAITING_LANGUAGE', 'Awaiting Language Choice'), ('AWAITING_EMAIL', 'Awaiting Email'), ('AWAITING_OTP', 'Awaiting OTP'), ('AWAITING_DOSE_RESPONSE', 'Awaiting Dose Response')], default='IDLE', max_length=30),
        ),
    ]
