# Generated by Django 5.0.4 on 2026-09-15 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('agent_name', models.CharField(max_length=50)),
                ('tool_name', models.CharField(max_length=100)),
                ('input', models.JSONField(default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (dry run)')], default='EXECUTED', max_length=20)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'agent_runtime_actions',
            },
        ),
        migrations.CreateModel(
            name='AgentGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('agent_name', models.CharField(max_length=50)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('goal_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], db_index=True, default='ACTIVE', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_runtime_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('agent_name', models.CharField(max_length=50)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('memory_type', models.CharField(max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('importance', models.FloatField(default=0.5)),
                ('confidence', models.FloatField(default=0.5)),
            ],
            options={
                'db_table': 'agent_runtime_memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approval_type', models.CharField(max_length=100)),
                ('required_role', models.CharField(blank=True, max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='agent_runtime.agentaction')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_runtime_approvals',
            },
        ),
        migrations.AddField(
            model_name='agentaction',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='agent_runtime.agentgoal'),
        ),
        migrations.CreateModel(
            name='AgentOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('outcome', models.CharField(blank=True, max_length=200)),
                ('success', models.BooleanField(null=True)),
                ('metric_before', models.JSONField(blank=True, default=dict)),
                ('metric_after', models.JSONField(blank=True, default=dict)),
                ('evaluation', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='agent_runtime.agentaction')),
            ],
            options={
                'db_table': 'agent_runtime_outcomes',
            },
        ),
        migrations.CreateModel(
            name='AgentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('steps', models.JSONField(default=list)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='agent_runtime.agentgoal')),
            ],
            options={
                'db_table': 'agent_runtime_plans',
            },
        ),
    ]
