# Generated by Django 5.0.4 on 2026-09-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='agentapproval',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='agentoutcome',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='agentplan',
            options={'ordering': ['-created_at']},
        ),
    ]
